import QtQuick
import Quickshell

// This file is generated by the Qt configurator.
// Manual edits will be overwritten the next time you save.
QtObject {
    id: userConfig

    property string wallpaperPath: Quickshell.home + "/.config/hypr/wallpaper.png"
    property real workspaceOverviewWindowRadius: 12
    property string iconFontFamily: "JetBrainsMono Nerd Font"
    property string textFontFamily: "Inter Display"
    property string heroFontFamily: "Inter Display"
    property string timeFontFamily: "Inter Display"
    // Plain-text sudo password for TLP mode switches.
    // Leave empty to use only cached sudo.
    property string tlpSudoPassword: ""

    // Set these to `0` if you want to disable the in-overview key handling.
    property int overviewCloseKey: 16777216
    property int overviewPreviousWorkspaceKey: 16777234
    property int overviewNextWorkspaceKey: 16777236

    // This registers a Hyprland global shortcut action for the workspace overview.
    property string overviewGlobalShortcutAppid: "quickshell"
    property string overviewGlobalShortcutName: "dynamic-island-overview"

    // Mouse buttons in this file use simple numbers:
    // 1 = left click, 2 = middle click, 3 = right click.
    // These fields are meant to use the simple numbers above, not Qt's raw enum values.

    // Workspace overview mouse bindings.
    property int workspaceOverviewWorkspaceActivateButton: 1
    property int workspaceOverviewWindowDragButton: 1
    property int workspaceOverviewWindowFocusButton: 1
    property int workspaceOverviewWindowCloseButton: 3

    // Dynamic Island mouse bindings.
    // Supported click actions:
    // "none", "toggleExpandedPlayer", "openExpandedPlayer", "closeExpandedPlayer",
    // "toggleControlCenter", "openControlCenter", "closeControlCenter",
    // "toggleOverview", "openOverview", "closeOverview",
    // "toggleLyrics", "showLyrics", "showTime", "restoreRestingCapsule"
    property int dynamicIslandSwipeButton: 1
    property int dynamicIslandPrimaryButton: 1
    property string dynamicIslandPrimaryAction: "toggleExpandedPlayer"
    property int dynamicIslandSecondaryButton: 3
    property string dynamicIslandSecondaryAction: "toggleControlCenter"
    property int dynamicIslandMouseRotation: 0
    // Supported built-in left swipe items:
    // "time", "date", "battery", "volume", "brightness", "workspace", "cpu", "ram", "cava"
    property var dynamicIslandLeftSwipeItems: (["cava","battery"])

    property var controlCenterIcons: ({
        "charging": "",
        "brightness": "󰃟",
        "volume": "󰕾"
    })

    property var statusIcons: ({
        "default": "🎧",
        "notification": "",
        "volume": "󰕾",
        "mute": "󰝟",
        "brightnessLow": "󰃞",
        "brightnessMedium": "󰃟",
        "brightnessHigh": "󰃠",
        "charging": "",
        "discharging": "",
        "cpu": "󰍛",
        "ram": "󰘚",
        "capsLockOn": "",
        "capsLockOff": "",
        "bluetooth": "󰋋"
    })

    function mouseButton(button) {
        switch (button) {
        case 1:
            return Qt.LeftButton;
        case 2:
            return Qt.MiddleButton;
        case 3:
            return Qt.RightButton;
        default:
            return typeof button === "number" ? button : Qt.NoButton;
        }
    }

    function mouseButtonsMask(buttons) {
        if (buttons === undefined || buttons === null)
            return Qt.NoButton;

        if (Array.isArray(buttons)) {
            let mask = Qt.NoButton;
            for (let index = 0; index < buttons.length; index++)
                mask |= mouseButton(buttons[index]);
            return mask;
        }

        return mouseButton(buttons);
    }
}
